from . import scoring_package
from . import scoring_package_line
from . import scoring_criterion
from . import scoring_period_criterion
from . import scoring_period
from . import vendor_score
from . import vendor_score_line
from . import res_company
from . import res_config_settings
from . import res_partner
from . import product_supplierinfo
from . import demo_data_generator
